#!/usr/bin/env python3
"""Regenerate root catalog.toml from each plugin's plugin.toml.

Personal/light version of community-plugins' catalog updater: no push secrets,
no monorepo-only guards — just rewrite the index from disk.
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "catalog.toml"
REQUIRED = ("id", "name", "version", "author", "plugin_api", "tags")
OPTIONAL_STR = ("license", "icon", "description")
OPTIONAL_BOOL = ("deprecated",)
OPTIONAL_LIST = ("dependencies",)


def load_manifest(path: Path) -> dict:
    with path.open("rb") as handle:
        data = tomllib.load(handle)

    missing = [field for field in REQUIRED if field not in data]
    if missing:
        raise ValueError(f"{path.relative_to(ROOT)} missing: {', '.join(missing)}")

    plugin_api = data["plugin_api"]
    if not isinstance(plugin_api, int) or isinstance(plugin_api, bool) or plugin_api <= 0:
        raise ValueError(f"{path.relative_to(ROOT)} invalid plugin_api")

    if not isinstance(data["tags"], list) or not all(isinstance(t, str) for t in data["tags"]):
        raise ValueError(f"{path.relative_to(ROOT)} tags must be a string array")

    out = {field: data[field] for field in REQUIRED}
    for field in OPTIONAL_STR:
        if field in data and isinstance(data[field], str):
            out[field] = data[field]
    for field in OPTIONAL_BOOL:
        if field in data and isinstance(data[field], bool):
            out[field] = data[field]
    for field in OPTIONAL_LIST:
        if field in data and isinstance(data[field], list):
            out[field] = data[field]
    return out


def existing_order() -> dict[str, int]:
    if not CATALOG.exists():
        return {}
    ids = re.findall(r'(?m)^id\s*=\s*"([^"]+)"', CATALOG.read_text(encoding="utf-8"))
    return {plugin_id: index for index, plugin_id in enumerate(ids)}


def discover() -> list[dict]:
    order = existing_order()
    plugins: list[dict] = []
    for path in sorted(ROOT.glob("*/plugin.toml")):
        if path.parent.name.startswith("."):
            continue
        item = load_manifest(path)
        item["_directory"] = path.parent.name
        item["_order"] = order.get(item["id"], len(order))
        plugins.append(item)
    plugins.sort(key=lambda p: (p["_order"], p["_directory"]))
    return plugins


def q(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(plugins: list[dict]) -> str:
    lines = [
        "# Auto-generated by .github/scripts/update_catalog.py — do not hand-edit.",
        "# plugin.toml in each subdirectory is authoritative; host re-reads it on enable.",
        "",
    ]
    for index, plugin in enumerate(plugins):
        if index:
            lines.append("")
        lines.extend(
            [
                "[[plugin]]",
                f"id = {q(plugin['id'])}",
                f"name = {q(plugin['name'])}",
                f"version = {q(plugin['version'])}",
                f"author = {q(plugin['author'])}",
            ]
        )
        if "license" in plugin:
            lines.append(f"license = {q(plugin['license'])}")
        if "icon" in plugin:
            lines.append(f"icon = {q(plugin['icon'])}")
        if "description" in plugin:
            lines.append(f"description = {q(plugin['description'])}")
        if "deprecated" in plugin:
            lines.append(f"deprecated = {'true' if plugin['deprecated'] else 'false'}")
        lines.append(f"plugin_api = {plugin['plugin_api']}")
        lines.append("tags = [" + ", ".join(q(tag) for tag in plugin["tags"]) + "]")
        deps = plugin.get("dependencies")
        if isinstance(deps, list) and deps:
            lines.append(
                "dependencies = [" + ", ".join(q(str(d)) for d in deps) + "]"
            )
    return "\n".join(lines) + "\n"


def main() -> int:
    plugins = discover()
    CATALOG.write_text(render(plugins), encoding="utf-8")
    print(f"Wrote {CATALOG.relative_to(ROOT)} with {len(plugins)} plugin(s).")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:  # noqa: BLE001
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1) from error
